"""add invite_code to user

Revision ID: 28d3442aa0e7
Revises: a91866141024
Create Date: 2019-08-17 10:37:40.737634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d3442aa0e7'
down_revision = 'a91866141024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invite_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invite_code')
    # ### end Alembic commands ###
